import './globals.css';
import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import {getServerSession} from 'next-auth';
import {authOptions} from '@/lib/auth';

export const metadata:Metadata={metadataBase:new URL(process.env.NEXT_PUBLIC_APP_URL||'http://localhost:3000'),title:{default:'Fuguaa | Ghanaian Smocks & Traditional Craft',template:'%s | Fuguaa'},description:'Discover authentic Ghanaian smocks and handwoven clothing from verified artisans across Ghana.',keywords:['Fuguaa','Ghanaian smocks','Ghana smocks','traditional Ghanaian clothing','handwoven smocks','African fashion'],icons:{icon:'/fuguaa-mark.png'},openGraph:{title:'Fuguaa | Three generations of craft',description:'A marketplace for authentic Ghanaian smocks and traditional craft.'}};

function firstName(name?:string|null){return String(name||'there').trim().split(/\s+/)[0]||'there'}

export default async function Layout({children}:{children:React.ReactNode}){
 const session=await getServerSession(authOptions); const signedIn=!!session?.user; const first=firstName(session?.user?.name);
 return <html lang="en"><body className="font-sans"><header className="sticky top-0 z-50 border-b bg-white/95 backdrop-blur"><div className="container-x flex h-16 items-center justify-between gap-4"><Link href="/" className="flex shrink-0 items-center gap-3"><Image src="/fuguaa-mark.png" alt="Fuguaa" width={46} height={46} className="h-11 w-11 object-contain"/><span><span className="block text-xl font-black tracking-tight">Fuguaa</span><span className="hidden text-[10px] uppercase tracking-[.25em] text-terracotta sm:block">Three generations of craft</span></span></Link><nav className="hidden items-center gap-6 md:flex"><Link href="/shop">Shop</Link><Link href="/cart">Cart</Link></nav><div className="ml-auto flex items-center gap-3">{signedIn?<Link className="text-sm font-bold text-terracotta" href="/account">Hello, {first} · Account</Link>:<Link className="text-sm font-bold text-terracotta" href="/auth/login">Sign in</Link>}<Link className="btn btn-primary text-sm" href="/signup">Start shopping</Link></div></div></header>{children}<footer className="mt-20 border-t bg-ink text-white"><div className="container-x grid gap-10 py-14 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><Image src="/fuguaa-mark.png" alt="" width={42} height={42} className="h-10 w-10 object-contain"/><div className="text-2xl font-black">Fuguaa</div></div><p className="mt-3 text-sm leading-6 text-white/70">Traditional Ghanaian craftsmanship, brought to modern wardrobes.</p></div><div><h3 className="font-bold">Shop</h3><div className="mt-3 space-y-2 text-sm text-white/70"><Link className="block" href="/shop">All Smocks</Link><Link className="block" href="/shop?occasion=wedding">Wedding</Link><Link className="block" href="/shop?occasion=festival">Festival</Link><Link className="block" href="/shop?occasion=children">Children</Link></div></div><div><h3 className="font-bold">For sellers</h3><div className="mt-3 space-y-2 text-sm text-white/70"><Link className="block" href="/signup/seller">Become a Seller</Link><Link className="block" href="/auth/login?next=%2Fseller-onboarding">Seller Login</Link><Link className="block" href="/seller-guide">Seller Guide</Link></div></div><div><h3 className="font-bold">Support</h3><div className="mt-3 space-y-2 text-sm text-white/70"><Link className="block" href="/help">Help Center</Link><Link className="block" href="/shipping-returns">Shipping & Returns</Link><Link className="block" href="/privacy">Privacy</Link><Link className="block" href="/terms">Terms</Link></div></div></div><div className="border-t border-white/10 py-5 text-center text-xs text-white/50"><Link href="/dashboard/admin" aria-label="Admin" title="Admin" className="transition hover:text-white">©</Link> {new Date().getFullYear()} Fuguaa · Crafted in Ghana.</div></footer></body></html>}
