export type Country={name:string;code:string;dial:string;regions:string[]};
export const countries:Country[]=[
{name:'Ghana',code:'GH',dial:'+233',regions:['Ahafo','Ashanti','Bono','Bono East','Central','Eastern','Greater Accra','North East','Northern','Oti','Savannah','Upper East','Upper West','Volta','Western','Western North']},
{name:'Nigeria',code:'NG',dial:'+234',regions:['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue','Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','Gombe','Imo','Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa','Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba','Yobe','Zamfara','FCT Abuja']},
{name:'United States',code:'US',dial:'+1',regions:['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming','District of Columbia']},
{name:'United Kingdom',code:'GB',dial:'+44',regions:['England','Scotland','Wales','Northern Ireland']},
{name:'Canada',code:'CA',dial:'+1',regions:['Alberta','British Columbia','Manitoba','New Brunswick','Newfoundland and Labrador','Nova Scotia','Ontario','Prince Edward Island','Quebec','Saskatchewan','Northwest Territories','Nunavut','Yukon']},
{name:'South Africa',code:'ZA',dial:'+27',regions:['Eastern Cape','Free State','Gauteng','KwaZulu-Natal','Limpopo','Mpumalanga','Northern Cape','North West','Western Cape']},
{name:'Kenya',code:'KE',dial:'+254',regions:['Central','Coast','Eastern','Nairobi','North Eastern','Nyanza','Rift Valley','Western']},
{name:'Germany',code:'DE',dial:'+49',regions:['Baden-Württemberg','Bavaria','Berlin','Brandenburg','Bremen','Hamburg','Hesse','Lower Saxony','Mecklenburg-Vorpommern','North Rhine-Westphalia','Rhineland-Palatinate','Saarland','Saxony','Saxony-Anhalt','Schleswig-Holstein','Thuringia']},
{name:'France',code:'FR',dial:'+33',regions:['Auvergne-Rhône-Alpes','Bourgogne-Franche-Comté','Brittany','Centre-Val de Loire','Corsica','Grand Est','Hauts-de-France','Île-de-France','Normandy','Nouvelle-Aquitaine','Occitanie','Pays de la Loire','Provence-Alpes-Côte d’Azur']},
{name:'United Arab Emirates',code:'AE',dial:'+971',regions:['Abu Dhabi','Dubai','Sharjah','Ajman','Umm Al Quwain','Ras Al Khaimah','Fujairah']},
{name:'Australia',code:'AU',dial:'+61',regions:['Australian Capital Territory','New South Wales','Northern Territory','Queensland','South Australia','Tasmania','Victoria','Western Australia']},
{name:'India',code:'IN',dial:'+91',regions:['Andhra Pradesh','Delhi','Goa','Gujarat','Haryana','Karnataka','Kerala','Maharashtra','Punjab','Rajasthan','Tamil Nadu','Telangana','Uttar Pradesh','West Bengal']},
{name:'China',code:'CN',dial:'+86',regions:['Beijing','Chongqing','Guangdong','Guangxi','Hainan','Hebei','Henan','Hubei','Hunan','Jiangsu','Jiangxi','Jilin','Liaoning','Shandong','Sichuan','Yunnan','Zhejiang','Hong Kong','Macau']},
{name:'Japan',code:'JP',dial:'+81',regions:['Hokkaido','Aomori','Iwate','Miyagi','Akita','Yamagata','Fukushima','Ibaraki','Tochigi','Gunma','Saitama','Chiba','Tokyo','Kanagawa','Niigata','Nagano','Shizuoka','Aichi','Osaka','Kyoto','Hyogo','Hiroshima','Fukuoka','Okinawa']},
{name:'Brazil',code:'BR',dial:'+55',regions:['Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Pará','Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins']},
{name:'Mexico',code:'MX',dial:'+52',regions:['Aguascalientes','Baja California','Baja California Sur','Campeche','Chiapas','Chihuahua','Coahuila','Colima','Durango','Guanajuato','Guerrero','Hidalgo','Jalisco','Mexico City','Michoacán','Morelos','Nayarit','Nuevo León','Oaxaca','Puebla','Querétaro','Quintana Roo','San Luis Potosí','Sinaloa','Sonora','Tabasco','Tamaulipas','Tlaxcala','Veracruz','Yucatán','Zacatecas']},
{name:'Other',code:'OTHER',dial:'+',regions:[]}
];
export const countryByName=(name:string)=>countries.find(c=>c.name===name)||countries[0];
